### ISSUE TITLE
How to get sales paginated data

### ISSUE THREAD

**Issue by starship-ibc** [public-awesome/constellations-book#5]
I'm trying to get sales events using the cursor pagination, but get a 502 Gateway Error when attempting to query beyond the first page.

Example query (against endpoint: https://constellations-api.mainnet.stargaze-apis.com/graphql):

```graphql
query Sales {
  events(
    first: 50
    after: "eyJCbG9ja0hlaWdodEFuZENyZWF0ZWRBdEFuZElkIjpbODAyMDAxMywiMjAyMy0wNS0wMVQyMTowOTowNy4yMzI4NjEiLCJjZDU4MzkwYy0wOTdjLTQyYzItYTE2MC03MjU3NDAzZTIyNjIiXX0"
    filter: SALES,
    sortBy: BLOCK_HEIGHT_DESC
  ) {
    edges {
      node {
        txHash
        createdAt
        data
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
```

Removing the `after` cursor works, but I'm unable to get the 2nd page of data, even when limiting the number of events to fewer than 50. Thank you.

**Comment by penso** [comment]
I think it's a bug, I'll look this week

**Comment by penso** [comment]
This is solved. Thanks!
